apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: nginx-test
  name: nginx-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - image: 192.168.0.2:5000/admin/nginx-test:${tag}
          imagePullPolicy: Always
          name: nginx-test
          ports:
            - containerPort: 80
              protocol: TCP
