apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: mytest
  name: mytest
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
        - image: 192.168.0.2:5000/admin/nginx-test:${tag}
          imagePullPolicy: Always
          name: mytest
          ports:
            - containerPort: 80
              protocol: TCP
