apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytest
  name: mytest
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
        - image: registry-vpc.cn-beijing.aliyuncs.com/acr-poc/cicd:${tag}
          imagePullPolicy: Always
          name: mytest
          ports:
            - containerPort: 80
              protocol: TCP
